migration:
  name: "nombre_migracion"
  description: "descripcion_de_la_migracion"
  version: "version"
  author: "nombre_del_autor"

tables:
  nombre_tabla_1:
    source:
      schema: "nombre_esquema"
      table: "nombre_tabla"
    target:
      schema: "nombre_esquema"
      table: "nombre_tabla"
    enabled: true/false
    migrationType: "full/incremental"
    incrementalConfig:
      column: "nombre_columna"
      type: "tipo_de_columna"
      startValue: "valor_inicial"
      batchSize: numero_de_filas
    filters:
      where: "condicion SQL"
    transformations:
      columns:
        nombre_columna:
          rename: "nuevo_nombre"
          type: "tipo_destino"
          trim: true/false
          nullDefault: "valor"
          caseTransform: "uppercase/lowercase"
